/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const WatchProduct = IDL.Record({
  'id' : IDL.Nat,
  'collection' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'price' : IDL.Float64,
  'material' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'addSeedDataAvantGarde' : IDL.Func([], [], []),
  'addSeedDataHeritage' : IDL.Func([], [], []),
  'addSeedDataPrecision' : IDL.Func([], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(WatchProduct)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [WatchProduct], ['query']),
  'getProductsByCollection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WatchProduct)],
      ['query'],
    ),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const WatchProduct = IDL.Record({
    'id' : IDL.Nat,
    'collection' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'price' : IDL.Float64,
    'material' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'addSeedDataAvantGarde' : IDL.Func([], [], []),
    'addSeedDataHeritage' : IDL.Func([], [], []),
    'addSeedDataPrecision' : IDL.Func([], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(WatchProduct)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [WatchProduct], ['query']),
    'getProductsByCollection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WatchProduct)],
        ['query'],
      ),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };